# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Build with Docker

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
      - name: Build with Maven
        run:
          mvn clean package
      - name: Start server process
        uses: JarvusInnovations/background-action@v1
        with:
          run:
            java -cp tinfoil-web/target/tinfoil-web-1.0-SNAPSHOT.jar me.mourjo.main.Server
          wait-on:
            http-get://localhost:7002/visits/all/someone
          wait-for: 1m
      - name: Fire requests to the server via curl
        run:
          curl -s -X 'POST' 'http://localhost:7002/visit/albert-heijn/mourjo' && echo "" && curl -s -X 'GET' 'http://localhost:7002/visits/all/mourjo'
